# -------------------------------
# ConfigMap (NON-CONFIDENTIAL)
# -------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
  labels:
    component: shipping
    tier: backend
    project: roboshop
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql
---
# -------------------------------
# Shipping Deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    tier: backend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      tier: backend
      project: roboshop
  template:
    metadata:
      labels:
        component: shipping
        tier: backend
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: joindevops/shipping:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shipping-config
---
# -------------------------------
# Shipping Service
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    tier: backend
    project: roboshop
spec:
  type: ClusterIP
  selector:
    component: shipping
    tier: backend
    project: roboshop
  ports:
  - port: 8080
    targetPort: 8080
